language: node_js
node_js:
 - "node"
env:
 - PLATFORM_SERVICE=platform_login
 - PLATFORM_SERVICE=platform_logout
 - PLATFORM_SERVICE=create-serverless-service
 - PLATFORM_SERVICE=delete-serverless-service
 - PLATFORM_SERVICE=is-service-available
 - PLATFORM_SERVICE=platform_services
script: cd $PLATFORM_SERVICE && npm install && npm test
