service: api-template-java
artifact: api-java-template-1.0.jar
mainClass: com.slf.services.Handler
securityGroupIds: {inst_security_group_id}
subnetIds: {inst_subnet_ids}
providerRuntime : java8
providerMemorySize : 256
providerTimeout : 160
region: us-east-2
domain: platform
# Put your custom role here which has the IAM permissions required by your code
iamRoleARN: {inst_role_lambda_basic_execution} 
