# Welcome to Serverless!
# For full config options, check the docs:
#    docs.serverless.com

service: ${file(deployment-env.yml):service}

provider:
  name: aws
  deploymentBucket: oaa-apis-deployment-${opt:stage}
  region: ${file(deployment-env.yml):region}
  stage: dev
  owner: ""
  domain: ""
  stackTags:
    application: jazz
    service: jazz::service:${file(deployment-env.yml):service}
    domain: jazz::domain:${file(deployment-env.yml):domain, self:provider.domain}
    owner: jazz::owner:${file(deployment-env.yml):owner, self:provider.owner}
    environment: jazz::environment::${opt:stage, self:provider.stage}

custom:
  myStage: ${opt:stage, self:provider.stage}
# This settings will be enabled once equivalent Java plugin is added.
#  alerts:
#    topics:
#      alarm: ${self:service}-${opt:stage}-alerts-alarm
#    global:
#      - functionThrottles
#      - functionErrors
#      - functionInvocations
#      - functionDuration
#
#plugins:
#  - serverless-plugin-aws-alerts

package:
  artifact: target/${file(deployment-env.yml):artifact}

functions:
  handler:
    name: ${file(deployment-env.yml):service}
    handler: ${file(deployment-env.yml):mainClass}
    role: ${file(deployment-env.yml):iamRoleARN}
    description: ${self:service} Lambda Function
    runtime: ${file(deployment-env.yml):providerRuntime}
    memorySize: ${file(deployment-env.yml):providerMemorySize}
    timeout: ${file(deployment-env.yml):providerTimeout}
    eventsDisabled:
      - schedule:
          rate: ${file(deployment-env.yml):eventScheduleRate}
          name: ${self:service}-${self:custom.myStage}-schedule
          enabled: ${file(deployment-env.yml):eventScheduleEnable}
    vpcDisabled:
      securityGroupIds:
        "Fn::Split":
          - ","
          - ${file(deployment-env.yml):securityGroupIds}
      subnetIds:
        "Fn::Split":
          - ","
          - ${file(deployment-env.yml):subnetIds}
